repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
        stages: [pre-commit]

      - id: pytest
        name: pytest-suite
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        env:
          PYTHONDONTWRITEBYTECODE: "1"

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
