#!/usr/bin/env python3
"""CLI wrapper to generate PyTorch Geometric state graphs from mutated state dicts."""

import argparse
from pathlib import Path
import torch
from polarity_engine.builder import ProteinGraphBuilder


def parse_args():
    parser = argparse.ArgumentParser(description="Build PyTorch Geometric state graph.")
    parser.add_argument(
        "--input", type=Path, required=True, help="Path to input mutated state .pt file"
    )
    parser.add_argument(
        "--state-code", type=str, required=True, help="Binary state code (e.g., '100')"
    )
    parser.add_argument(
        "--cutoff",
        type=float,
        default=8.0,
        help="Distance cutoff threshold in Angstroms",
    )
    parser.add_argument(
        "--output", type=Path, required=True, help="Output PyG graph .pt file path"
    )
    return parser.parse_args()


def main():
    args = parse_args()

    if not args.input.is_file():
        raise FileNotFoundError(
            f"Input mutated dictionary file not found: {args.input}"
        )

    # Load mutated state dictionary generated by MUTATE_STATE
    parsed_dict = torch.load(args.input, weights_only=False)

    # Initialize ProteinGraphBuilder with interaction cutoff
    builder = ProteinGraphBuilder(distance_cutoff=args.cutoff)

    # Construct PyTorch Geometric Data object
    graph_data = builder.build_from_parsed_dict(
        parsed_dict=parsed_dict, name=f"state_{args.state_code}"
    )

    # Attach state code metadata
    graph_data.state_code = args.state_code

    # Save compiled PyG Data object
    out_path = Path.cwd() / args.output.name
    torch.save(graph_data, out_path)


if __name__ == "__main__":
    main()
